from typing import Protocol


class StorageProvider(Protocol):
    def get_file(self, file_path: str) -> str: ...

    def upload_file(self, file, filename: str, tags: dict): ...

    def delete_all_files(self) -> None: ...

    def delete_file(self, file_path: str) -> None: ...
